# Generated by Django 4.1 on 2022-08-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromFactry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('cost_price', models.IntegerField()),
                ('in_date', models.DateField()),
                ('total_in', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bac_app.fromfactry')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.ImageField(upload_to='', verbose_name='qty')),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bac_app.fromfactry')),
            ],
        ),
    ]
